categories = ["movies", "shows", "songs", "random"]
songs = ['#selfie', '(fuck a) silver lining ', '100 letters', '1800-278-255', '25 to life', '2u', '3000 miles',
         '50 ways to say goodbye', '679', '7 years', 'a thousand years', 'a year without rain', 'addicted',
         'adore you', 'afire love', 'airplanes', 'alive', 'all about that bass', 'all around the world',
         'all falls down', 'all i wanted', 'all of me', 'all of the lights', 'all of the stars', 'all the right moves',
         'all these years', 'all time low', 'all we know', 'almost love', 'alone', 'alone together', 'am i wrong',
         'american beauty american psycho', 'amityville', 'amnesia', 'amsterdam', 'angel on fire', 'angel', 'animals',
         'another day in paradise', 'anything, anything', 'anywhere', 'apologize', 'applause', 'area', 'army', 'arose',
         'as long as you love me', 'as you are', 'ashtrays and heartbreaks', 'ass back home', 'asshole', 'astronaut',
         'atlas', 'attention', 'awkward', 'babe', 'back in time', 'back to december', 'back to me', 'back to you', 'bad at love',
         'bad husband', 'bad romance', 'bad together', 'bailamos', 'bailando', 'bang bang', 'barcelona', 'battle scars', 'be the one',
         'be with you', 'beautiful monster', 'beautiful now', 'beautiful pain ', 'beautiful world', 'beautiful', 'beauty and a beat',
         'bedroom floor', "beggin'", 'begging', 'believe', 'believer', "bella's lullaby", 'berzerk', 'best day of my life', 'best friend',
         'better than i know myself', 'better than revenge', 'bibia be ye ye', 'big girls cry', 'billionaire', 'birthday',
         'bishops knife trick', 'bittersweet', 'black widow', 'blame', 'blank space', 'bleeding out', "blood's thicker than water",
         'bloodstream', 'bloom', 'blow me (one last kiss)', 'blow your mind (mwah)', 'blow', 'body on me', 'bohemian rhapsody', 'bon appetite',
         'boom boom pow', 'boom clap', 'born this way', 'born to be yours', 'born to live', 'both of us ', 'boulevard of broken dreams',
         'boy like you', 'boyfriend', 'brave', 'break free', 'break your heart', 'breakeven', "breathin'", 'bridge of light', 'bring me to life',
         'brokenhearted', 'bromance', 'bucket list', 'bulletproof love', 'bulls in the bronx', 'bumpy ride', 'burn it down', 'burn', "burnin' up",
         'but a dream', "but it's better if you do", "c'mon", 'cake by the ocean', 'california gurls', 'call it what you want', 'call me a spaceman',
         'call me maybe', 'call on me ', 'call out my name', 'calling all my lovelies', 'calypso', 'can we dance', 'can you feel my heart',
         "can't feel my face", "can't hold us", "can't stop the feeling!", 'carol of the bells', 'carry on', 'cars , clothes and calories',
         'castle of glass', 'castle on the hill', 'castle', 'casual affair', 'catch my breath', 'cave in', 'center of the universe',
         'centuries', 'chained to the rhythm', 'champion', 'chandelier', 'charles brown', 'chasing the sun', 'cheap thrills', 'cheerleader',
         'chloraseptic ', 'chunky', 'church', 'cinderella man', 'city in a garden', 'clarity', 'classic', 'clean up anthem', 'closer further',
         'closer', 'closing time', "club can't handle me", 'cold water', 'cold wind blows', 'cold', 'colors', 'colors pt. ii', 'come & get it',
         'coming down', 'coming home', 'complicated', 'connection', 'control', 'cool ', 'cool for the summer', 'cornfield chase', 'could this be love',
         'counting stars', 'crash & burn', 'crazier', 'crazy kids', 'crazy=genius', 'criminal', 'crying in the club', 'cups', 'dance again',
         'dance to this', 'dance with me tonight', 'dancing in the dark', 'dancing with our hands tied', "dancing's not a crime ", 'dangerous woman',
         'dangerously', 'danza kuduro', 'dare', 'dark horse', 'dark side', 'darkside', 'daylight', 'dead man walking', 'dead memories',
         'death of a bachelor', 'death valley', 'delicate', 'demons', 'dental care', 'despacito', 'dessert', 'devil in me', 'diamonds',
         'die young', 'dinero', 'dirty dancer', 'distance', 'dive', 'does it feel', 'domino', "don't blame me", "don't let me down",
         "don't stop the music", "don't stop the party", "don't stop the pop", "don't stop", "don't threaten me with a good tim", "don't wake me up",
         "don't you worry child", 'dong saya dae', 'dont leave me', 'dont wanna know', 'don_t play', 'down  ', 'downtown dead', 'dreams', 'dress', 'drive by',
         'drive', 'drunk', 'duality', 'dusk till dawn ', 'dynamite', 'e.t.', 'eastside', 'eazy', 'eenie meenie', 'elastic heart', 'electricity',
         "emperor's new clothes", 'empire state of mind', 'empty gold', 'end game', 'english love affair', 'entertainer', 'eraser', 'eulogy',
         'evacuate the dancefloor', 'even my dad does sometimes', 'every breath you take', 'every night', 'every teardrop is a waterfall', 'everybody hates me ',
         'everything has changed', "everything i didn't say", "everything's gonna be alright", 'eyes closed', 'fade', 'faded', 'fall in line', 'fall', 'falling',
         'fame == infamy', 'fancy', 'rocketeer', 'far too young to die', 'fast car', 'favorite record', 'fearless', 'feel good', 'feel it still', 'feel this moment',
         'feel', 'feeling sorry', 'feelings', 'feels', 'fetish', 'fickle game', 'fifteen', 'filthy', 'finale', 'finesse', 'fireflies', 'firework', 'first love',
         'first time', 'five more hours', 'fix you', 'flashlight', 'flicker', 'fly away', 'fly', 'fools', 'for you', 'forbidden voices', 'forever and always',
         'four pink walls', 'fourth of july', 'framed', 'friends', 'g.u.y.', 'galway girl', 'gangnam style', 'garden', 'gasoline', 'genesis', 'gentleman',
         'get low', 'getaway car', 'ghost', 'girl that you love', 'girls like you', 'girls girls boys', 'give me everything', 'give me love', 'glad you came',
         'god is a woman', "god's plan ", 'gold', 'golden days', 'gone, gone, gone', 'good for you', 'good goodbye', 'good guy', 'good intentions', 'good mourning',
         'gorgeous', 'got the feeling', 'gotdamn', 'grade 8', 'greatest', 'green light', 'greenback boogie', 'grenade', 'growing pains', 'halfway right',
         'hall of fame', 'hallelujah', 'halo', 'hands to myself', 'happier', 'happy now', 'happy', 'hasta la vista', 'haunting', 'havana', 'he like that',
         'hear me', 'heart attack', 'heartbeat', 'heartbreaker ', 'heartbreaker', "hearts don't break around here", 'heat', 'heathens', 'heaven in hiding',
         "heaven's gate", 'heavy ', 'hello seattle', 'hello', 'here ', 'here i am', 'heroes (we could be)', 'hey brother', 'hey look ma i made it ',
         'hey, soul sister', 'hide away', 'high hopes', 'highway to hell', 'him & i', "hips don't lie", 'hold me down', 'hold me tight or don_t', 'homesick',
         'honest', "honey, i'm good", 'hope you do', 'hopeless ft. cashmere cat', 'hotel california', 'hotline bling', 'hotter than hell', 'house of memories ',
         'how deep is your love', 'how long', 'how would you feel ', 'human', 'humble.', 'hurricane', 'hurt you', 'hymn for the weekend',
         "i can't stop drinking about you", 'i could be the one', 'i did something bad', "i don't know why", "i don't wanna live forever ", 'i feel it coming ',
         'i hate u i love u', 'i knew you were trouble', 'i know what you did last summer', 'i like how it feels', 'i like it', 'i like me better', 'i lived',
         'i love it', 'i need a doctor', 'i need your love', 'i really like you', 'i see fire', 'i took a pill in ibiza ', 'i walk the line', 'i wanna go',
         'i wanna know ', 'i wanna know', 'i was never there', 'i will survive', "i won't tell a soul", 'i write sins not tradgedies', "i'd love to change the world",
         "i'll be gone", "i'll be there for you", "i'm a mess", "i'm yours", 'i.c.y.m.i.', 'idgaf', 'if i lose myself', 'if my heart was a house ',
         'if you could see me now', 'ignored ', 'imagination', 'immortals', 'impossible year', 'in my blood ', 'in my feelings', 'in the end',
         'in the name of love', 'in the night', 'in your head', 'innocence', 'inside out', 'instruction', 'international love', 'into it', 'into you',
         'irresistible ft. demi lovato', 'irresistible', 'is there somewhere', 'issues', "it ain't me", "it's a beautiful day", "it's time",
         'i_ll make it up to you', 'jet black heart', 'jet pack blues', 'juju on that beat', 'jump', 'just can_t get enough', 'just give me a reason',
         'just like fire', 'just like you', 'just one yesterday', 'just the way you are', 'kamikaze', 'keep on keeping on', 'kennedy center performance',
         'kill em with kindness', 'killshot', 'king of my heart', 'king', 'kiss me', 'la botella', 'la devotee', 'lake effect kid', 'last dance',
         "lavender's blue", 'lean on ', 'left right left', 'legacy', 'legend', 'legendary', 'lego house', 'leh', 'let her go', 'let it go', 'let it whip',
         'let me go', 'let me love you', 'let me', 'let you be right', 'let you go ', "let's go to the mall", 'letters from the sky', 'levels', 'leviathan',
         'lie ', 'light it up ', 'light that never comes', 'lights', 'like home ', 'like i would', 'like im gonna lose you', 'like my daddy', 'live it up',
         'locked away', 'locked out of heaven', 'lonely together', 'look what you made me do', 'lose my mind', 'lose yourself', 'losing my mind', 'lost in japan',
         'lost in the echo', 'lost in your light ', 'love is gone', 'love me again ', 'love of my life', 'love somebody', 'love story', 'love the way you lie ',
         'love yourself', 'lovely', 'loyalty', 'lucid dream', 'lucky you', 'lullaby', 'lush life', 'mad world ', 'made in the usa', 'magic', 'make you believe',
         'mama always told me', 'mama', 'maneater', 'maps', 'marry the night ', 'marvin gaye ', 'me & my girls', 'me and my broken heart', 'me too',
         'me, myself & i', 'mean', 'meant to be ', 'memories', 'mercy ', 'meteor shower', 'middle', 'milkshake', 'millennial love ', 'mine', 'mirrors',
         'misery', 'miss jackson ', 'miss missing you', 'mmm yeah', 'moments ', 'monster', 'more than this', 'morning light', 'most girls', 'mouth of the river',
         'move shake drop', 'move your body', 'moves like jagger', 'mr. saxobeat', 'my gospel', 'my heart is broken', 'my heart will go on', 'my house',
         'my immortal', 'my my my!', 'my name is', 'my song', 'my songs know what you did in the da', 'naked', 'nancy mulligan', 'natural', 'need me ',
         'neon lights', 'never be the same ', 'never forget you', 'never let it die', 'never let me go', 'never say never', 'new americana ', 'new love',
         'new man', 'new rules', "new year's day", 'new york city ', 'new york city', 'new', 'nice guy', 'nice guys', 'nicotine', 'nina', 'no brainer',
         'no doubt about it', 'no excuses', 'no goodbyes', 'no less', 'no lie', 'no limit', 'no love', 'no more sad songs', 'no promises ',
         'no tears left to cry', 'no way home', 'no', 'nobody can save me', 'normal', 'not afraid', 'not alike', "nothin' on you ", 'nothing but trouble',
         'nothing to lose', 'nothing', 'novocaine', 'now or never', 'nowhere fast ', 'numb', 'offended', 'oh cecilia (breaking my heart)', 'oh glory ',
         'oh wonder', 'old fashioned ', 'omg', 'on & on', 'on my mind', 'on the loose', 'on the wing', 'on top of the world', 'one call away', 'one dance',
         'one day at a time', 'one day', 'one foot', 'one last time', 'one love', 'one more light', 'one more night', 'one of the drunks ', 'one that got away',
         'one thing', 'one', 'only hope', 'only you', 'ordinary love', 'other side of love', 'out of the woods', 'outlaws', 'outside', 'overboard', 'overdose',
         'paparazzi', 'parachute', 'paradise', 'paris', 'part of me', 'party in the u.s.a.', 'party rock anthem', 'payphone', 'peivilege', 'people like us',
         'perfect places', 'perfect', 'perm', 'phantoms and friends', 'phoenix', 'photograph', 'pick me up', 'pictures', 'pillowtalk', 'pills & automobiles',
         'play hard', 'power', 'powerless', 'pray for me', 'price tag', 'princess of china', 'promises', 'questions', "quit playin' games", 'r.i.p.',
         'radioactive ', 'radioactive', 'raging fire', 'rain over me', 'rainbow', 'rap devil', 'rap god', 'rat a tat ', 'rather be', 'ready to go ',
         'real friends', "really don't care", 'red lights', 'red', 'remember me', 'remember when', 'remind me', 'replay', 'rhythm divine', 'rich love',
         'ride', "ridin' solo", 'right now', 'right round', 'rise up', 'rise', 'ritual', 'river of tears', 'river', 'roads untraveled', 'roar', 'roaring 20s ',
         'robbers', 'rock bottom', 'rock the boat', 'rock your body', 'rockabye', 'rocket', 'rockstar', 'rolling in the deep', 'roman holiday', 'room for 2',
         'roses', 'royals', 'rude boy', 'rude', 'runaway', "runnin' home to you", 'safe & sound', 'safe and sound', 'safe', 'salute', 'same old love', 'sanctify',
         'satellite', 'saturday', 'save myself', 'save rock and roll', 'savior', 'say ', 'say amen (saturday night)', 'say something', "say you won't let go",
         'scared to be lonely', 'scars to your beautiful', 'scream & shout', 'scream', 'seasons in the sun', 'seasons', 'secrets', 'see you again', 'send it on ',
         'september song', 'set fire to the rain', 'setting fires', 'seventeen', 'sexy and i know it', 'sexy bitch', 'shake it off', 'shape of you',
         "she doesn't mind", 'she looks so perfect', 'she loves control', 'she will be loved', 'she wolf ', 'shine', 'ship to wreck', 'shirtsleeves',
         'shots', 'should i stay or should i go', 'show me', 'shower', 'shut up and dance', 'sick boy', 'side effects', 'sign of the times', 'silhouettes',
         'since u been gone', 'sing me to sleep', 'sing', 'sit still, look pretty', 'six degrees of separation', 'skyfall', 'skyscraper', 'sledgehammer',
         'slide', 'slow down', 'smack that', 'small bump', 'smile', 'smoke and mirrors', 'snitch bitch', 'snuff', 'so it goes...', 'sober', 'some nights',
         'some type of love', 'somebody that i used to know', 'somebody to love remix', "somebody's me", 'somebody', 'someone like you',
         'something in the way you move', 'something just like this', "something's gotta give", 'sorry not sorry', 'sorry', 'space bound',
         'spectrum', 'starboy ', 'stars', 'starships', 'start again', 'start over', 'started from the bottom ', 'starving', 'state of grace',
         'stay frosty royal milk tea', 'stay stay stay', 'stay the night', 'stay with me', 'stay', 'stepping stone', 'stereo hearts', 'stereo love',
         'still got time', 'still into you', 'stitches', 'straight up and down', 'strange love', 'stranger things', 'strangers ', 'stressed out',
         'strip that down', 'stronger ', 'style', 'sucker for pain', 'suffer', 'sugar', 'summer in december', 'summer', 'summertime sadness ',
         'sunshine riptide', 'super bass', 'super fade', 'super lover', 'superhero', 'superheroes', 'supermarket flowers', 'supplies', 'surrender',
         'surround me', 'swalla ', 'sweet escape ', 'sweet home alabama', 'sweet nothing', 'swish swish', 'symphony ', 'take a picture', 'take it all away',
         'take it back', 'take it off', 'take me to church', 'take over control', 'talk dirty ', 'talk me down', 'talk', "talkin' 2 myself ", 'talking body',
         'talking to myself', 'talking to the moon', 'taste the feeling', 'team', 'teardrops on my guitar', 'teenage dream', 'telephone', 'tell me you love me',
         'temperature', 'ten feet tall', 'tenerife sea', 'tennis court', 'thanks for the memories', 'that power', "that's a lot", "that's my kind of night",
         "that's my name", 'the a team', 'the alphabeat', 'the ballad of mona lisa', 'the beautiful & damned', 'the bird and the worm', 'the calendar',
         'the city', 'the climb', 'the cure', 'the end', 'the fighter', 'the final countdown', 'the good, the bad and the dirty', 'the greatest',
         'the heart wants what it wants', 'the hills', "the kids aren't alright", 'the last of the real ones', 'the light is coming', "the man who can't be moved",
         'the man', 'the middle', 'the mighty fall', 'the monster', 'the night out - madeon remix', 'the night we met', 'the only difference between marty',
         'the other side', 'the overpass ', 'the plan', 'the prologue', 'the ringer', 'the saltwater room', 'the scientist', 'the sound', 'the story of us',
         'the time ', 'the tip of the iceberg', 'the village', "then there's you", 'there for you', 'there she goes', "there's nothing holdin' me back",
         "these things i've done", "thinking 'bout you", 'thinking about you', 'thinking out loud', 'thirsty', 'this is gospel', 'this is how we do', 'this is me',
         'this is what you came for', "this one's for you", "this summer's gonna hurt like a moth", 'this', 'thousand miles', 'thrift shop ', 'throw your hands up',
         'thunder', 'thunderclouds', 'tidal wave', 'tik tok', 'timber', 'time after time', 'time', 'titanium', 'tko', 'to build a home', 'told me',
         "tonight (i'm lovin' you)", 'tonight i_m getting over you', 'too good at goodbyes', 'too good to say goodbye', 'toothbrush', 'tootimetootimetootime ',
         'touch', 'toxic', 'tragic endings ', 'trap queen', 'treasure', 'treat you better', 'tremor ', 'trouble ', 'troublemaker', 'true love ', 'try me', 'try',
         'trying to be cool', 'turn around', 'turn down for what', 'turn me on', 'turn off the lights', 'turn the night up', 'turn up the music',
         'turn up the speakers', "twin skeleton's (hotel in nyc)", 'two black cadillacs', 'u.n.i', 'u12', 'uma thurman', 'umbrella beach', 'umbrella',
         'unconditionally', 'unstoppable', 'untouchable', 'up all night', 'uptown funk', 'vanilla twilight', 'vegas lights', 'venom', 'versace on the floor',
         'victorious', 'wait', 'waka waka (this time for africa) ', 'wake me up', 'walk on water', 'walkin in hawkins', 'walking the wire', 'walks like rihanna',
         'walls could talk', 'want you back', 'warzone', 'wasted times', 'watch me ', 'water fountain', 'waves', "wavin' flag",
         'we are never ever getting back together', 'we are one (ole ola) ', 'we are young', 'we are', "we can't stop", "we don't talk anymore ",
         'we found love', 'we own the night', 'we run the night', 'welcome to my life', 'what about love', 'what about us', 'what do i know', 'what do you mean',
         'what lovers do', 'what makes you beautiful', 'what now', 'what you wanted', 'whatever it takes', 'when i was your man', "when i'm gone lyrics",
         'when we were young', "when you're gone", 'whenever, wherever', 'where are you now', 'where did the party go', 'where have you been', 'whistle',
         "who's it gonna be", 'why try', 'wicked ones', 'wide awake', 'wiggle', 'wild ones', 'wild things', 'wild', 'wildest dreams',
         'wilson (expensive mistakes)', 'wing$', 'wish you were here', 'with you', 'without you', 'wizard', 'wolves', "won't back down ", 'wonders',
         'words', 'work from home', 'work', 'worth it', 'wrapped up', 'wrecking ball', 'written in the stars ', 'yeah!', 'yesterday', 'you & i',
         'you are the reason', 'you belong with me', 'you make me feel...', 'you make me', "you need me i don't need you", 'you owe me', 'young and menace',
         'young god', 'young volcanoes', 'young', 'youngblood', 'younger now', 'your love is my drug', 'youth', 'zombie']
movies = ["the conjuring", "the conjuring 2", "annabelle", "annabelle creation", "the nun",
          "insidious", "insidious chapter 2", "insidous chapter 3", "insidious the last key",
          "the ring", "the ring 2", "rings", "amityville the awakening", "iron man", "iron man 2",
          "iron man 3", "captain america the first avenger", "captain america winter soldier",
          "captain america civil war", "avengers", "avengers age of ultron", "avengers infinity war",
          "doctor strange", "spiderman homecoming", "ant man", "ant man and the wasp", "black panther",
          "grown ups", "grown ups 2", "just go with it", "blended", "the blind side", "the game plan", "titanic",
          "extremely loud and incredibly close", "gravity", "the martian", "interstellr", "the prestige",
          "shutter island", "dunkirk", "the shawshank redemption", "inception", "dont mess with the zohan",
          "finding nemo", "finding dory", "moana", "justice league", "the dark knight rises", "wonder woman",
          "ouija origin of evil", "rush hour", "rush hour 2", "rush hour 3", "who am i", "the tuxedo",
          "independence day", "independence day resurgence", "mean girls", "mean girls 2", "pitch perfect",
          "pitch perfect 2", "pitch perfect 3", "guardians of the galaxy", "guardians of the galaxy vol2",
          "inside out", "cars", "cars 2", "cars 3", "thor", "thor the dark world", "thor ranganrock", "casper",
          "ghostbusters", "ghostbusters II", "ghostbusters III", "batman vs superman dawn of justice",
          "scary movie", "scary movie 2", "scary movie 3", "final destination", "final destination 2",
          "final destination 3", "final destination 4", "final destination 5", "the silence of the lambs",
          "dont breathe", "lights out", "there's something about mary", "mr & mrs smith", "mission impossible",
          "mission impossible 2", "mission imposible III", "mission impossible ghost protocol", "camp rock",
          "mission impossibe rogue nation", "mission impossible fallout", "the parent trap", "planes",
          "high school musical", "high school musical 2", "high school musical 3", "premonition", "get out",
          "orphan", "mama", "shutter", "we're the millers", "the forest"]
shows = ["stranger thing", "f.r.i.e.n.d.s", "how i met your mother", "riverdale", "supernatural", "dark",
         "house m.d", "the mentalist", "the suite life of zack and cody", "castle", "suits", "quantico",
         "brooklyn nine nine", "suite life on deck", "2 broke girls", "atypical", "the good doctor", "x-factor",
         "13 reasons why", "white collar", "pretty little liars", "teen wolf", "one tree hill", "american idol",
         "america's got talent", "fresh off the boat", "the goldbergs", "marvel's iron fist", "the simpsons", "young sheldon",
         "the flash", "arrow", "modern family", "breaking bad", "man with a plan", "sherlock", "a series of unfortunate events",
         "monk", "revenge", "wizards of waverly place", "black mirror", "empire", "how to get away with murder",
         "impractica jokers", "spongebob squarepants", "blues clues", "beyblade", "lucifer", "Marvel's luke cage",
         "marvel's the punisher", "masterchef australia", "masterchef u.s.a", "orange is the new black",
         "prison beak", "the end of the f***ing world", "the walking dead", "legends of tommorow", "supergirl"]
random = songs+movies+shows
